# Generated by Django 5.1.5 on 2025-02-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_reservation_room_delete_person_reservation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(default='Unknown Guest', max_length=50),
        ),
    ]
