# Generated by Django 5.1.5 on 2025-02-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_remove_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
