# Generated by Django 5.1.5 on 2025-02-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0004_alter_reservation_adults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
