# Generated by Django 5.1.5 on 2025-02-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0005_alter_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='card_holder',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='reservation',
            name='card_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cvv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='exp_month',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='exp_year',
            field=models.IntegerField(blank=True, default=2030, null=True),
        ),
    ]
